.eslintrc.js, index.js, jest.config.js, lib/index.js, lib/server.js, package.json, rollup.config.js, rollup.test.config.js, shims/pretender-node.js
This needs a check-in / review.
* Changes the rollup config to build for esm, cjs, and umd. `package.json` `module` will point at the esm, and `main` will point at index, which redirects to cjs. 
* Jest will run the integration tests against each of the bundles. These tests will fail, because they're importing files from lib. We can change these to use all public API. Probably should not enable these tests right now.
=> [WIP] Rollup config, and jest integration tests against builds

package.json
This way build tools consuming the cjs module will be have a real pretender, since they're building for the web.
=> Use real pretender in package.json's browser field

lib/utils/extend.js
When the UMD build is uglified, uglify removes assignment which causes Parent to become undefined. This change prevents uglify from removing the assignment by proactively removing the assignment.
=> Remove assignment to Parent because ugly thinks its a variable that's never used

package.json, yarn.lock
We wrongfully removed corejs in https://github.com/miragejs/server/pull/113
because we thought using the options to our rollup babel plugin to enable
the polyfill didn't need it as a dependency. We were wrong!
=> Add back in corejs@3

lib/orm/associations/belongs-to.js, lib/orm/associations/has-many.js, lib/orm/schema.js, lib/server.js, lib/utils/inflector.js, package.json
=> refactor: memoize some methods

lib/orm/model.js
This reduces the amount of loops that are done during hydration when setting models up.
See example on how often `_setupAttrs` and `_setupRelationships` are called:
This also replaces some `arr.indexOf()` calls with `arr.includes` as includes is already used elsewhere to check if an array includes an item).
**Note**: this has to rebased if the other PRs are merged.
I could also move all the changes into one bigger PR if that's easier to review.
=> refactor: reduce loop count during model setup

__tests__/external/shared/factories/create-and-create-list-test.js, jest.config.js, package.json, yarn.lock
- adds corejs
- The inflection test in the create-and-create-list test module previously
worked by configuring the `inflected` package in a global/mutable way.
(This is actually the package's recommended way of configuring inflections.)
But Mirage accepts a custom "inflector" if you just pass in a pluralize
and singularize string.
Since I wanted to also verify inflections could be customized for the UMD
build, and the UMD build doesn't work with inflected's default customizations
(since it's not referencing the global/imported version of that pacakge),
it made sense to refactor these tests to have the "caller" pass in
pluralize/singularize. That way, they'd work for all builds. It also
better reflects how folks should actually customize Mirage inflections.
=> Fix UMD build

lib/orm/associations/belongs-to.js, lib/orm/associations/has-many.js, lib/orm/model.js, lib/orm/schema.js, lib/serializers/json-api-serializer.js, lib/server.js
Both `associationKeys` and `associationIdKeys` are primarily used to check if a key is included in them.
They're looked up repeatedly when setting up attrs.
I've changed them to a Set because:
* `set.has` should be something like closes to O(1)  (see also [microbenchmark](http://jsben.ch/TFCDD)`*`)
* Set is still [supported by IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility)
This PR also extracts the static arguments from server.create/createList as they never change on each invocation.
`*` = microbenchmarks are never perfect
Using https://gist.github.com/makepanic/241013f4dd94d6064d046642d60c43d2 to benchmark this change, I'm getting:
// master
setup x 13.14 ops/sec ±16.22% (24 runs sampled)
setup x 12.84 ops/sec ±17.21% …
=> perf: use Set for association(Id)Keys

lib/orm/model.js
This removes the times mirage iterates over model attributes during setup.
Before it iterated over n attrs:
* 2x in `_setupAttrs`
* 1x in `_setupRelationships`
This doesn't seem that much but a model instance is created all the time due to [hydration](https://github.com/miragejs/server/blob/master/lib/orm/schema.js#L537).
This PR changes the behavior to only iterate once over all attrs.
This will also allow further optimization to skip relationship setup if the attr is an attribute (I'm not sure if mirage allows that though).
Using https://gist.github.com/makepanic/241013f4dd94d6064d046642d60c43d2 to benchmark this change, I'm getting:
// master
setup x 13.14 ops/sec ±16.22% (24 runs sampled)
setup x 12.84 ops/sec ±17.21% (24 runs sampled)
// model-cycles
setup x 13.32 ops/sec ±16.96% (24 …
=> perf(model): remove attr iterations when creating a model instance

lib/route-handlers/shorthands/delete.js, lib/route-handlers/shorthands/put.js
Before this PR the shorthand route handlers would return a Internal Server Error because `.find(id)` returns `undefined` and calling a method on `undefined` throws an error. This PR adds a check to both handlers that matches the behavior of the `GET` shorthand handler.
=> route-handlers/shorthands: Return 404 from PUT/DELETE if model can't be found

__tests__/external/shared/factories/helpers-test.js, lib/server.js
I stumbled upon this while working on the app so decided why not fix it :-)
Basically foreign key validation for polymorphic expects `{ type, id }` object here:
https://github.com/miragejs/miragejs/blob/4ab442d1570625e8ccfdfed04f5c7c87d1269350/lib/orm/model.js#L712-L714
=> Throw when association helper is used with polymorphic belongsTo

lib/server.js
This fixes the GitHub issue links in the API docs for `namespace` in the "Server" class where the link was getting the GitHub 404 error page.
=> Fix GitHub issue link in API docs

__tests__/external/browser-only/passthrough-test.js, lib/server.js
Currently, passing a function to the `passthrough` method will break if the "request to be passthrough" has queryParams.
This PR fixes it
=> Fix passthrough function with queryParams

lib/server.js
- Adds esdoc types for `Server` constructor arguments
Related https://github.com/miragejs/site/pull/199
If both are merged, docs will be as shown on the link ☝️
=> docs: Add server options types

types/index.d.ts, types/tests/server-test.ts
fix #392
- Add `fixtures` property to `ServerConfig` interface. At the moment it is a vague `any`, we can be more specific later and force strict type configuration.
=> Add missing fixtures property to ServerConfig type definition

types/index.d.ts, types/tests/relationships-test.ts, types/tests/schema-test.ts
Chatting with @samselikoff yesterday about possible paths forward for #396, I had an 'aha moment' around dealing with the typing for relationships between models. What's currently in place requires some boilerplate to work with TypeScript, in order to introduce registry-aware versions of the `belongsTo` and `hasMany` functions. It's also a bit fragile in the face of highly-interconnected sets of models, as you have to be careful not to trip the typechecker's circular type declaration alarms.
This PR addresses both of those problems by reworking the types of relationships not to carry the full type of the model they're related to, but rather only the name of that model in the registry. The actual type is resolved on-demand when the key is referenced, eliminating the risk of the typechecker …
=> Simplify typed usage of relationships

types/index.d.ts, types/tests/serializer-test.ts, types/tests/server-test.ts
fix #396 
- Add Serializer classes
- Very loose types, it can be more strict after the Serializer is refactored and cleaned up.
=> Add basic Serializer type support

__tests__/internal/unit/server-test.js, lib/index.js, lib/server.js, types/index.d.ts, types/tests/server-test.ts
@samselikoff we had a conversation about this a little over a month ago, and I went and implemented it but then never actually committed the files and opened a pull request 🤦 
This PR introduces a `createServer` function as an alternative to writing `new Server`. While it doesn't add any new functionality, it does have a couple of advantages:
- It avoids having consumers of the library call a side-effecty constructor (whether that's a code smell or not is a matter of personal opinion, but it's certainly been the topic of lots of angsty blog posts)
- It allows for type-safe interactions with the server in the context of your config, which was the last lingering topic of discussion in #396.
In other words, if I write `schema.all('foo')` in a route handler, TypeScript can tell based on the …
=> Introduce `createServer`

package.json
Prior to this change, Webpack (in common tools like Create React App + Vue CLI) would not tree-shake Mirage from production builds, since Mirage does indeed have side effects. However, these side effects are only relevant during development, and should not prevent Mirage from being tree-shaken from production builds.
The `sideEffects` key is an escape hatch and can be used to tell Webpack exactly this. With this change, apps with modern build setups that use Mirage like this
```js
import { Server } from 'miragejs'
if (process.env.NODE_ENV === 'production') {
new Server()
}
```
should get all of `miragejs` automatically tree-shaken from their production builds!
=> Mark Mirage as tree-shakable via sideEffects key

types/index.d.ts, types/tests/overview-test.ts
There's a small hiccup in the current `DbLookup` type which `db` uses.
Eg. if you have something like `schema.db.model`, the type of the model is `DbCollection` which is actually wrong because of what `db.createCollection` does:
```
// Public API has a convenient array interface. It comes at the cost of
// returning a copy of all records to avoid accidental mutations.
Object.defineProperty(this, name, {
get() {
let recordsCopy = newCollection.all();
[
"insert",
"find",
"findBy",
"where",
"update",
"remove",
"firstOrCreate",
].forEach(function (method) {
recordsCopy[method] = function () {
return newCollection[method](...arguments);
};
});
return recordsCopy;
},
});
```
There's no `db.model.all()` function as the `DbCollection` type suggests. This PR changes the `DbLookup` type to match …
=> Fix DbLookup type for db

types/index.d.ts, types/tests/factory-test.ts
There's a small limitation of the current types in that we can't use functions within factory definitions. This fixes it so that we can.
This should fix https://github.com/miragejs/examples/issues/9 by making it so that we don't need to use the property-getter workaround
=> [TS] Basic support for functions in factories

types/tests/server-test.ts
It seems the types changed a little in TS 4.0, so I've removed the $ExpectType that has been causing CI to fail.
=> Fix CI: Remove type assertion that fails in TS 4.0

types/index.d.ts
I found that miragejs handles `this.head` route handlers just fine, but the signature was missing from the types.  So this adds it.
=> Add type for head request handler

.github/workflows/ci.yml, .travis.yml
Travis has run out of credits, and github actions are more than powerful enough to run linting and tests, and in fact we can run against all the versions of node that are supported, to ensure no breaking changes are made accidentally.  
I've left the release job in travis for now, we can figure out what to do with that before the next time we need to release.
=> Move to github actions for CI

package.json, yarn.lock
This updates the version of dtslint from 4.0.6 to 4.1.6.
~~It also removes the direct dependency on typescript~~ Edit: That didn't work out, typescript does seem to still need to be installed for dtslint to run.
=> Update dtslint to 4.1.6

yarn.lock
This updates the final direct dependencies being reported by `yarn outdated`, which are all part of the build toolchain.  
```
@babel/core       7.12.10 -> 7.15.5
@babel/preset-env 7.12.11 -> 7.15.6
core-js             3.8.1 -> 3.18.1
rollup             2.35.1 -> 2.58.0
```
=> Update rollup, babel, core-js

yarn.lock
Now that all of our direct dependencies are updated, this PR updates all of the transitive dependencies (sub-dependencies).  I did this by deleting the `yarn.lock` file, and re-creating it.  This allows semver to do its thing and de-duplicate as many dependencies as possible, which actually reduces the total number of packages installed in the mirage repo from 1024 to 960.
This isn't something I'd recommend doing all the time, but every once in a while I think it's good cleanup to do.
=> Update transitive dependencies

types/index.d.ts, types/tests/factory-test.ts, types/tests/model-test.ts
I've found that I sometimes need to get the attributes of a model, but typescript was typing as a generic unknown object.  I _think_ we can type it the same as the properties that are added directly to the model itself, based on the wording of https://miragejs.com/api/classes/model/#attrs.
=> Add more useful typescript type for `modelInstance.attrs`

package.json, types/tests/collection-test.ts
`prettier:update` was applied to all files, but `prettier:check` only ran against javascript files, which means that `.ts` files could become incorrectly formatted and CI wouldn't detect it.
This adds typescript files to the formatting check, and formats the only file that was not already conforming to the prettier styles.
=> Enforce prettier in typescript files

README.md, types/index.d.ts, types/tests/collection-test.ts, types/tests/server-test.ts
This updates the types for `RouteHandler` to allow for any valid JSON response. Adds `number | string | boolean | null` as well as arrays of `object | number | string | boolean | null`.
This is necessary because endpoint can return more than just an object. For instance the project I'm currently working on adding mirage too has an endpoint that returns just a number. Which is totally valid however using the current types without this change causes typescript to emit an error.
=> Route handler return types

__tests__/internal/unit/schema-test.js, lib/orm/schema.js, types/index.d.ts, types/tests/db-test.ts
=> Add a type for findBy with a predicate function

__tests__/external/shared/orm/belongs-to/1-basic/association-set-test.js, __tests__/internal/move-after-handle-request/get-full-path-test.js, lib/index.js, lib/mock-server/pretender-config.js, lib/server.js
This PR moves all the pretender related code to the file `mock-server/pretender-config` and conditions the creation of pretender on the presence of an additional server option `interceptor`.
The goal of this PR was to be fully backward compatible. It opens up the ability to replace the interceptor with a different interceptor or allow for no interceptor at all.
First step towards https://github.com/miragejs/miragejs/issues/1013
=> Extract pretender code to its own module for future move to another package

lib/mock-server/pretender-config.js, lib/server.js
Fixed the assert that informed you could not change the trackRequests after pretender is created. 
After moving things around, the value of tracked Request was being sent into pretender via a function. The value in the function was being set too late. Since the value was already known, just simplified as putting it behind a function served no purpose.
Fixes https://github.com/miragejs/miragejs/issues/1043
=> Removed assert about changing Pretender config. Ensured trackRequest was set properly

lib/mock-server/pretender-config.js, lib/server.js
Fixes: https://github.com/miragejs/miragejs/issues/1049
This required a change to the contract for pretender being extracted and updating the extracted pretender. Since we have not removed the internal pretender code yet, this version will work. Should anyone be using the extracted version of pretender at https://github.com/bgantzler/mirage-pretender, that will break until I update that repo as well. Since it hasnt been officially released (waiting for this repo to settle down and shake out bugs, this issue being a prime example), I dont think it will be an issue. 
There were no tests testing this sort of thing to update and I didnt write any as Im not sure exactly how to test it given its the communication between mirage and pretender and kinda happens behind the scenes, which might have …
=> Fixed timing being incorrectly passed to pretender

lib/mock-server/pretender-config.js, types/index.d.ts, types/tests/server-test.ts, types/tsconfig.json
It seems like passthrough type declaration is incorrect. It suggest that you can pass in array of for e.q strings. When we look on implementation passthrough is implemented as ```passthrough(...paths)```. Fix type. Using ```passthrough(['url1', 'url2'])``` will not work.
=> Align passthrough type declaration with implementation

lib/orm/model.js, types/index.d.ts, types/tests/relationships-test.ts
- Given:
```
type Model =  {
items: HasMany<Item>
}
```
- Current behavior:
```
ModelInstance<Model>.update({items: [item1, item2]}); // $ExpectError
ModelInstance<Model>.update({items: Collection<Item>});
```
- New behavior:
```
ModelInstance<Model>.update({items: [item1, item2]}); 
ModelInstance<Model>.update({items: Collection<Item>}); 
````
- Motivation: We should be able to use readily available/simple data types to update our models, instead of having to create a new `Collection` first before we can update.
=> Improve ModelInstance<Model>.update

__tests__/external/shared/serializers/base/associations/embedded-collection-test.js, lib/serializer.js
#850 introduced support for selectively serializing embedded relationships. 
This PR should close #1073 which points out a collision which was also introduced between `serializeIds` (set to `always` as it is in [the `ActiveModelSerializer`](https://github.com/miragejs/miragejs/blob/master/lib/serializers/active-model-serializer.js#L5) and [the `RestSerializer`](https://github.com/miragejs/miragejs/blob/master/lib/serializers/rest-serializer.js#L5)) and the intended new functionality.
=> Establish precedence for embed over serializeIds

__tests__/external/shared/serializers/base/id-key-formatting-test.js, __tests__/internal/unit/serializers/active-model-serializer-test.js, lib/serializer.js, lib/serializers/active-model-serializer.js, lib/serializers/rest-serializer.js
Replaces PR https://github.com/miragejs/miragejs/pull/417
=> Allow for keyForId and valueForId on the serializer

types/index.d.ts, types/tests/server-test.ts
This uses the type from https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L432 / https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L454
I think that https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L161 might contain the correct type for `params` a la #1026 but that seems to need better verification
=> Updates typing for `Request.queryParams`

__tests__/external/shared/serializers/base/basic-test.js, __tests__/external/shared/serializers/json-api-serializer/associations/key-for-relationship-test.js, __tests__/external/shared/serializers/json-api-serializer/key-formatting-test.js, __tests__/internal/move-after-handle-request/route-handlers/function-handler/serialize-test.js, lib/db-collection.js, lib/db.js, lib/factory.js, lib/mock-server/pretender-config.js, lib/orm/associations/has-many.js, lib/orm/collection.js, lib/orm/model.js, lib/orm/polymorphic-collection.js, lib/orm/schema.js, lib/serializer.js, lib/serializers/json-api-serializer.js, lib/server.js, lib/utils/extend.js, lib/utils/inflector.js, lib/utils/is-association.js, lib/utils/reference-sort.js, package.json, yarn.lock
The need for using the dedicated `lodash.assign` style dependencies has long since passed, so I have updated all uses to import from the one module and use the path import like this `import assign from 'lodash/assign'`
I have compared the output of the dist folder before and after this change and there are no differences for `esm` and `cjs` but `umd` has shaved off .5 MB from its size 😱 
Master: 
```
➜  miragejs git:(master) ls -l dist 
total 4776
-rw-r--r--  1 mansona  staff   223153 Oct 10 12:10 mirage-cjs.js
-rw-r--r--  1 mansona  staff   404879 Oct 10 12:10 mirage-cjs.js.map
-rw-r--r--  1 mansona  staff   269963 Oct 10 12:10 mirage-esm.js
-rw-r--r--  1 mansona  staff   403613 Oct 10 12:10 mirage-esm.js.map
-rw-r--r--  1 mansona  staff  1136772 Oct 10 12:10 mirage-umd.js
➜  miragejs …
```
=> Simplify lodash dependencies

__tests__/internal/move-after-handle-request/middleware-test.js, lib/route-handler.js, lib/server.js, types/index.d.ts
Relating to [Add Middleware support to Mirage #41 ](https://github.com/miragejs/discuss/issues/41).
This PR adds middleware to miragejs via a new `server.midleware = [...]`
Example middleware which randomly returns a 500 response:
```js
function random500() {
return (schema, req, next) => {
return (Math.random() > 0.7)
? new Response(500, {}, 'no')
: next();
}
}
```
Routes which use the middleware defined above: 
_(Edited to match latest update)_
```js
routes() {
this.middleware = [
random500(),
addABunchOfResponseHeaders(),
// more middleware can be added here...
]
// Subsequent routes will have that middleware
this.get('/users', (schema, req) => {
return new Response(204, {}, null);
});
this.middleware = [
// differentMiddleware
]
this.get('/frogs', (schema, req) => {
return new …
```
=> add Middleware support via `server.middleware = [/*...*/]`

__tests__/internal/move-after-handle-request/middleware-async-test.js
Well, my intent was to see what it would take to add async support to the recent middleware API, so I started adding tests... and the tests already pass with **no code changes necessary.**
There's a bit of gymnastics around the `MaybePromise` responses, but I think that's to be expected at this stage in the code.
=> add tests for async middleware

.github/workflows/ci.yml
The inexorable march of time has brought us new node.js versions and github actions.  Node 18 is the oldest active LTS, and the current LTS is 22.  
https://nodejs.org/en/about/previous-releases
=> Update github actions and node versions for CI

__tests__/internal/unit/server-test.js, lib/server.js, rollup.config.js, types/index.d.ts
This is to support MSW startup, which is async.  It has the downside of also making startup using pretender also async, even though it doesn't need to be.  Perhaps there's a bit of an inversion we can do here, so that the interceptors import from miragejs core, and users interact only directly with the interceptors.  I'll try experimenting around with something like that, but in the meantime, we could release this as an alpha version in case anyone wants to experiment with mirage-msw.  To that end, this PR is targeting a new `next` branch, to keep the main branch clean in case we need to release something (unlikely, I know).
=> Breaking: Make createServer async to support MSW.
