miragejs/miragejs

lib/index.js
package.json

- This was done but was broken on the re-extraction

Fix npm build and prepublish scripts

---

.eslintrc.js
.travis.yml
lib/db-collection.js
lib/orm/model.js
lib/response.js
lib/serializers/json-api-serializer.js
lib/server.js
package.json
yarn.lock

This adds a new npm script `test:all` that will lint and run tests.

Eslint all files

---

package.json

This fixes mirage in jest environments

For now we'll use umd

---

package.json
yarn.lock

Revert "build(deps-dev): bump rollup-plugin-alias from 1.5.2 to 2.0.0"

---

jest.config.js
rollup.config.js

Fix typo in esm build

---

rollup.config.js

Fixes https://github.com/miragejs/server/pull/114

Ensure ie11 support for ESM build

---

lib/db-collection.js
lib/orm/collection.js
lib/orm/model.js
lib/orm/polymorphic-collection.js
lib/serializer-registry.js

This probably won't affect performance in the common case.
This removes just some unnecessary array method calls.

refactor: replace some filter()[0] usages to avoid unneeded iterations

---

__tests__/internal/unit/route-handlers/shorthands/base-test.js
lib/route-handlers/base.js

fix: fix trailing slash regression during url model extraction

---

.gitignore
lib/server.js

Document shutdown

---

__tests__/internal/move-after-handle-request/regressions/1318-linkage-data-bug-test.js
__tests__/internal/move-after-handle-request/regressions/1322-relationship-path-normalization-test.js
__tests__/internal/move-after-handle-request/regressions/1613-two-bidirectional-many-to-many-with-same-target-model-update-bug-test.js
__tests__/internal/move-after-handle-request/regressions/many-to-many-bug-test.js
lib/server.js

Update API docs and tests to use routes

---

lib/server.js

Remove aside in passthrough docs

---

lib/orm/schema.js
lib/serializers/json-api-serializer.js

I had an issue with findBy, so I updated the docs a little bit.

Update documentation for `schema.js`

---

__tests__/internal/move-after-handle-request/serializers/includes-test.js
lib/serializer.js

Pass the primary resource to serializer.include()

---

package.json
types/index.d.ts
types/tests/db-test.ts
types/tests/factory-test.ts
types/tests/model-test.ts
types/tests/overview-test.ts
types/tests/relationships-test.ts
types/tests/schema-test.ts
types/tests/server-test.ts
yarn.lock

Fix TypeScript linting issues around Registry and Schema

---

package.json
yarn.lock

Upgrade pretender

---

lib/serializer.js

Use the imported serializer in the demo codeblock

Update serializer documentation

---

__tests__/external/shared/orm/attrs-test.js
lib/orm/model.js

Model.toJSON should copy attrs

---

package.json
yarn.lock

Fixes https://github.com/miragejs/miragejs/issues/814

fix: upgrade pretender to 3.4.7 fixing 

---

package.json
rollup.config.js
yarn.lock

rollup-plugin-node-resolve is not maintained, switch to @rollup/plugin-node-resolve

Switch to maintained @rollup/plugin-node-resolve

---

package.json
rollup.config.js
yarn.lock

Built on #748 , switch to @rollup/plugin-babel.

Update babel plugin

---

__tests__/external/shared/serializers/active-model-serializer-test.js
lib/serializer.js
types/index.d.ts

Support selected embedded relationships

---

types/index.d.ts
types/tests/server-test.ts

Adds the resource function type definition to the Server class

Add resource function type definition

---

__tests__/internal/move-after-handle-request/server-config-test.js
__tests__/internal/unit/server-test.js
lib/mock-server/pretender-config.js
lib/server.js

Closes https://github.com/miragejs/miragejs/issues/1079

Don't require testConfig for timing to respect environment.
